### ISSUE TITLE
Proper README

### ISSUE THREAD

**Issue by ashwini0529** [ashwini0529/git-repo#17]
A proper formatted README is required

**Comment by hpanago** [comment]
What exactly do you need on this one?

**Comment by ashwini0529** [comment]
@hpanago , A proper documentation of the repository.
That should contain the following things : 
- Description
- Installation Guidelines
- Examples (With Screenshots)
- Requirements
- Contribution Guidelines
- Language and tools used

You can look upon few readme files like [this](https://gist.github.com/PurpleBooth/109311bb0361f32d87a2)

**Comment by simocosimo** [comment]
#26
