### ISSUE TITLE
Issue displaying the number of followers and following of a User

### ISSUE THREAD

**Issue by simocosimo** [ashwini0529/git-repo#21]
When a User has more than 999 followers/following there's a problem.
Look at this case:

_GitHub counters_

![github-counters](https://cloud.githubusercontent.com/assets/5237492/19219734/0921aae8-8e1c-11e6-8c83-471e0d059f34.png)

_Script output_

![cmd-issue](https://cloud.githubusercontent.com/assets/5237492/19219737/143e076e-8e1c-11e6-8d5b-c1f9cd9fbf11.png)

The **'k'** is ignored.

**Comment by ashwini0529** [comment]
@simocosimo Have a look on it. Is this resolved now?

**Comment by simocosimo** [comment]
@ashwini0529 Never mind, it's ok now.
I'm about to PR some fixes

**Comment by ashwini0529** [comment]
@simocosimo Cool! :)
