### ISSUE TITLE
Update requirements file

### ISSUE THREAD

**Issue by ashwini0529** [ashwini0529/git-repo#23]
All the GUI libraries and other libraries are not added in the `requirements.txt` file

**Comment by jubrilissa** [comment]
Hi, @ashwini0529 PyQt4 is the only GUI libraries not in requirements.py file. And it can't be added like that. Or is there something else I am missing?
Can you expatiate, because I would like to take on this :simple_smile:

**Comment by sureshdsk** [comment]
@ashwini0529 updated requirements with all dependencies. Created a PR here https://github.com/ashwini0529/git-repo/pull/25 👍

**Comment by ashwini0529** [comment]
pyqt-4 does not work.
