### ISSUE TITLE
Project name conflict

### ISSUE THREAD

**Issue by jayvdb** [ashwini0529/git-repo#37]
Note there is another project which has reserved the name [git-repo on pypi](https://pypi.python.org/pypi/git-repo) and is hopefully [soon](https://github.com/guyzmo/git-repo/issues/139) part of the coala infrastructure.

In addition to renaming, you might want to consider merge some of your cool stuff into git-repo, or into [git-extras](https://github.com/tj/git-extras), which is packaged on Fedora and Ubuntu.

**Comment by ashwini0529** [comment]
Sure thing. I would love to add on few features to them. Also I'm working on the GUI part along with few developers.
The proposed prototype for GUI by one of the contributor is this: 
![prototype](https://cloud.githubusercontent.com/assets/8419333/24588079/355fb940-17df-11e7-824e-cbfcb9867e8a.png)

**Comment by jayvdb** [comment]
Rename done.  Thanks.
Re-open if you want help moving some of your goodies into more established repositories.
