### ISSUE TITLE
Possible Enhancement

### ISSUE THREAD

**Issue by munendrasn** [ashwini0529/git-repo#4]
I am adding few enhancements/suggestions. I have already covered one in #3. 
- [x] Check if user exists or not[ Gives 404] 
- [x] Check if given repo and user exist[similar to first]
- [x] Add `try except` wherever necessary
- [x] Change `contributions()`  to meet new `Github` modifications contribution Graph
- [x] Add `doc-strings` to functions

**Comment by ashwini0529** [comment]
Fixed 2nd issue in commit [b51e17c](https://github.com/ashwini0529/git-repo/commit/b51e17caddcbd87d1cfa7c5d3c2077edbde31972)

**Comment by munendrasn** [comment]
@ashwini0529 , How about adding doc-string to functions??

**Comment by ashwini0529** [comment]
That's a nice idea. @munendrasn , it would be great if you implement this.

**Comment by ashwini0529** [comment]
@munendrasn , did you see the Contributors bug?

**Comment by munendrasn** [comment]
I have been stuck in some other work from a while.
I will work on `contributions` after that.

**Comment by ashwini0529** [comment]
Perfect. We can close the issue after that.

**Comment by ashwini0529** [comment]
Closed in [8044960](https://github.com/ashwini0529/git-repo/commit/8044960fecc38dd643d6837bc22477a11aac875c)
