### ISSUE TITLE
gitfiles.py needs to be updated due to the UI change in Github profile #hacktoberfest

### ISSUE THREAD

**Issue by ashwini0529** [ashwini0529/git-repo#9]

**Comment by yatingupta10** [comment]
Could you tell me in which module are you facing problems?

**Comment by ashwini0529** [comment]
As you know that Github changed the user profile section. The class attributes are also changed. If you could work upon fixing up the gitfiles.py code, that would be a great help. :)

**Comment by yatingupta10** [comment]
can I use Selenium?

**Comment by ashwini0529** [comment]
Anything would be fine. :+1:

**Comment by ashwini0529** [comment]
But then you would have to change the code all over. I would not not prefer doing that.

**Comment by yatingupta10** [comment]
okay cool i will be working on it!
and update you in a week's time
i will look into it, if selenium is not required i won't!

**Comment by ashwini0529** [comment]
@hkmangla , @yatingupta10 would also be working on it.
We can distribute the work then.

**Comment by yatingupta10** [comment]
@ashwini0529  please assign the tasks, I don't want to create any confusion, I hope neither do you.
and kindly open another issue for specific tasks in gitfiles.py and kindly assign the issues
Otherwise at the end of the day we dont get to know who is doing what

**Comment by ashwini0529** [comment]
@yatingupta10 cool. I'll assign the tasks then.

**Comment by ashwini0529** [comment]
great job @hkmangla

**Comment by yatingupta10** [comment]
what is happening??
did he fix the issues?

**Comment by ashwini0529** [comment]
Yes @yatingupta10 
We'll add more features. I'll come up with the list of features.

**Comment by yatingupta10** [comment]
okay sure, kindly let me know when it is up!
I want to contribute to this project

**Comment by ashwini0529** [comment]
Yeah sure. :)
